### ISSUE TITLE
CSRF token stays valid trough-out multiple requests. Intended?

### ISSUE THREAD

**Issue by IvRRimum** [go-authboss/authboss-sample#17]
Hello,

You can use 1 CSRF token, for calling registration multiple times(for API as X-CSRF-TOKEN token).
Is this intended? 

Thanks!

**Comment by aarondl** [comment]
It doesn't sound right does it?

https://security.stackexchange.com/questions/22903/why-refresh-csrf-token-per-form-request

https://www.owasp.org/index.php/Cross-Site_Request_Forgery_(CSRF)_Prevention_Cheat_Sheet

It seems like the recommended defense does not require a unique token on each request. In reality the idea is to prevent Javascript on another page from calling our state changing endpoints with the user's authenticated cookies. If there is *any* CSRF token present the attack will fail since they cannot retrieve the results of a get request (and can't get the token). So it doesn't matter if it changes or not for the given session. Of course it's more secure to do a per request token, that would additionally defend against certain combination attacks possibly.

Owasp also notes in the second link that per-request CSRF tokens break functionality of the "back" button in the browser which isn't desirable.

Also note that it's not the sample's implementation so much as the use of the nosurf library that decided how this would work. Was good to read up on it though. And obviously if your needs were different you could use a different CSRF library. Thanks for filing the issue. Will consider this closed.
