### ISSUE TITLE
Bug occur when server restarts and browser sends back session data

### ISSUE THREAD

**Issue by jcjackchen** [go-authboss/authboss-sample#23]
How to reproduce the bug: The server first had some valid users(register and confirm with the usual routine) and restarts (lost all user information), and try to access an authed route with the original session(cookie), the server encounter an exception. 
 
![image](https://user-images.githubusercontent.com/25170947/48281927-12727980-e40d-11e8-96ab-824f0ca537fb.png)

Two way to stop this from happening: 
- Delete the `ab_blog` cookie before issue a request to an authed route after restarts
- register a new account before issue a request after restarts

It appears that in the function `layoutData` or the `dataInjector`,  even if it failed to load the current user, its `context` still contains the `pid` value, but I am not sure if this was related. 

I am new to Go, and doesn't really know how to modify the `context` to remove the `pid`, could you briefly explain how to do it or any other way to resolve this issue?

**Comment by aarondl** [comment]
Ah yeah. The sample is just programmed this way. This is sort of acceptable behavior from my perspective. Your app should not suddenly lose a user that was logged in - in the rare case that it does - this behavior is ok (the sample loses them every restart on purpose, again your app should not do this :D)

To delete a value you can just set it to nil in the context. Though I don't recommend you do this - better to make a middleware that deletes awkward session cookies like ones containing user ids that don't exist. Anyway, users who are logged in should not be deleted. If that's a use case your application needs to support than I suggest you create a middleware to purge stale sessions.

To be clear: This is by design for this project (authboss-sample) and it's up to your app to handle this case more correctly :)
